### ISSUE TITLE
BookWalker unicode error

### ISSUE THREAD

**Issue by whiteangel123** [xuzhengyi1995/Manga_downloader#14]
Not sure what I did wrong, but when I try to download from Bookwalker I get "unicode error: unicodeescape can't decode bytes"
The URL is member.bookwalker.jp, as mentioned. Did I maybe get the wrong cookie? :(

**Comment by xuzhengyi1995** [comment]
Hello,
Thank you for your question.
I think maybe you wrote the wrong path, if you are using Windows system, please make sure that the path you given is some thing like: "C:\\path\\to\\images\\manganame" or "C:/path/to/images/manganame" but never "C:\path\to\images\manganame", in many program, the \xxxx means this is a unicode, so if you want to input "\" you must use "\\".
If this not solve your problem, please give a full log, thank you!

**Comment by whiteangel123** [comment]
This is what happened:

`Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>e:

E:\>cd E:\Renta_Downloader-master\Manga_downloader-master

E:\Renta_Downloader-master\Manga_downloader-master>python main.py
  File "main.py", line 13
    'imgdir': 'E:\Renta_Downloader-master\Manga',
              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in positio
n 26-27: malformed \N character escape

E:\Renta_Downloader-master\Manga_downloader-master>`

**Comment by xuzhengyi1995** [comment]
Please change `main.py` line 13:
```python
'imgdir': 'E:\Renta_Downloader-master\Manga',
```
to
```python
'imgdir': 'E:\\Renta_Downloader-master\\Manga',
```

Then I think it can be run correctlly.
Thank you!

**Comment by whiteangel123** [comment]
Hello, it now runs, but nothing gets downloaded. Did I maybe get the URL of the manga wrong :( 
I copied the "member.bookwalker.jp", and not "viewer.bookwalker.jp".

**Comment by xuzhengyi1995** [comment]
I think the URL is ok, it will start with member.bookwalker.jp, normally this is because the cookies is wrong or maybe the network problem, could you give some logs please, it's easier to find out the reason, thank you.

**Comment by whiteangel123** [comment]
Hello! Which logs do I need to send? The CMD logs?

**Comment by whiteangel123** [comment]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>e:

E:\>cd E:\Renta_Downloader-master\Manga_downloader-master

E:\Renta_Downloader-master\Manga_downloader-master>python main.py

[INFO](root) 2020-09-28 02:46:26 : Find action class, use BookwalkerJP class.

DevTools listening on ws://127.0.0.1:54393/devtools/browser/723336e8-67df-49f6-a
512-89f3beca819d
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    downloader = Downloader(**settings)
  File "E:\Renta_Downloader-master\Manga_downloader-master\downloader.py", line
72, in __init__
    self.init_function()
  File "E:\Renta_Downloader-master\Manga_downloader-master\downloader.py", line
91, in init_function
    self.get_driver()
  File "E:\Renta_Downloader-master\Manga_downloader-master\downloader.py", line
84, in get_driver
    self.driver = webdriver.Chrome(chrome_options=option)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not crea
ted: This version of ChromeDriver only supports Chrome version 83


E:\Renta_Downloader-master\Manga_downloader-master>python main.py
  File "main.py", line 13
    'imgdir': 'E:\Renta_Downloader-master\Nobu',
              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in positio
n 26-27: malformed \N character escape

E:\Renta_Downloader-master\Manga_downloader-master>python main.py
[INFO](root) 2020-09-28 21:34:17 : Find action class, use BookwalkerJP class.

DevTools listening on ws://127.0.0.1:59374/devtools/browser/8fd6b6aa-19e9-434c-b
983-802e570e375b
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    downloader = Downloader(**settings)
  File "E:\Renta_Downloader-master\Manga_downloader-master\downloader.py", line
72, in __init__
    self.init_function()
  File "E:\Renta_Downloader-master\Manga_downloader-master\downloader.py", line
91, in init_function
    self.get_driver()
  File "E:\Renta_Downloader-master\Manga_downloader-master\downloader.py", line
84, in get_driver
    self.driver = webdriver.Chrome(chrome_options=option)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python38-32\lib\site-packages
\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not crea
ted: This version of ChromeDriver only supports Chrome version 83


E:\Renta_Downloader-master\Manga_downloader-master>
