### ISSUE TITLE
Message: javascript error: NFBR is not defined

### ISSUE THREAD

**Issue by mel0n0** [xuzhengyi1995/Manga_downloader#149]
I don't get it, My environment is macOS 13.5 (Intel), Python 3.11.4.
```
[INFO](root) 2023-08-13 17:44:58 : Preparing for downloading...
[INFO](root) 2023-08-13 17:45:18 : Run before downloading...
Traceback (most recent call last):
  File "/Users/vendor/Desktop/Manga_downloader/main.py", line 43, in <module>
    downloader.download()
  File "/Users/vendor/Desktop/Manga_downloader/downloader.py", line 212, in download
    self.download_book(t_img_dir)
  File "/Users/vendor/Desktop/Manga_downloader/downloader.py", line 143, in download_book
    self.actions_class.before_download(driver)
  File "/Users/vendor/Desktop/Manga_downloader/website_actions/bookwalker_tw_actions.py", line 58, in before_download
    for key in driver.execute_script('return Object.keys(NFBR.a6G.Initializer)'):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vendor/Desktop/Manga_downloader/bw/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 491, in execute_script
    return self.execute(command, {
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vendor/Desktop/Manga_downloader/bw/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/Users/vendor/Desktop/Manga_downloader/bw/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: NFBR is not defined
  (Session info: chrome=115.0.5790.170)
Stacktrace:
0   370bb2f5804b794d_chromedriver       0x0000000102b0c6b8 370bb2f5804b794d_chromedriver + 4937400
1   370bb2f5804b794d_chromedriver       0x0000000102b03b73 370bb2f5804b794d_chromedriver + 4901747
2   370bb2f5804b794d_chromedriver       0x00000001026c1616 370bb2f5804b794d_chromedriver + 435734
3   370bb2f5804b794d_chromedriver       0x00000001026c6adf 370bb2f5804b794d_chromedriver + 457439
4   370bb2f5804b794d_chromedriver       0x00000001026c99bf 370bb2f5804b794d_chromedriver + 469439
5   370bb2f5804b794d_chromedriver       0x0000000102744bce 370bb2f5804b794d_chromedriver + 973774
6   370bb2f5804b794d_chromedriver       0x0000000102729012 370bb2f5804b794d_chromedriver + 860178
7   370bb2f5804b794d_chromedriver       0x0000000102743e76 370bb2f5804b794d_chromedriver + 970358
8   370bb2f5804b794d_chromedriver       0x0000000102728de3 370bb2f5804b794d_chromedriver + 859619
9   370bb2f5804b794d_chromedriver       0x00000001026f6d7f 370bb2f5804b794d_chromedriver + 654719
10  370bb2f5804b794d_chromedriver       0x00000001026f80de 370bb2f5804b794d_chromedriver + 659678
11  370bb2f5804b794d_chromedriver       0x0000000102ac82ad 370bb2f5804b794d_chromedriver + 4657837
12  370bb2f5804b794d_chromedriver       0x0000000102acd130 370bb2f5804b794d_chromedriver + 4677936
13  370bb2f5804b794d_chromedriver       0x0000000102ad3def 370bb2f5804b794d_chromedriver + 4705775
14  370bb2f5804b794d_chromedriver       0x0000000102ace05a 370bb2f5804b794d_chromedriver + 4681818
15  370bb2f5804b794d_chromedriver       0x0000000102aa092c 370bb2f5804b794d_chromedriver + 4495660
16  370bb2f5804b794d_chromedriver       0x0000000102aeb838 370bb2f5804b794d_chromedriver + 4802616
17  370bb2f5804b794d_chromedriver       0x0000000102aeb9b7 370bb2f5804b794d_chromedriver + 4802999
18  370bb2f5804b794d_chromedriver       0x0000000102afc99f 370bb2f5804b794d_chromedriver + 4872607
19  libsystem_pthread.dylib             0x00007ff8138bf1d3 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8138babd3 thread_start + 15
```

**Comment by gwentgod** [comment]
Acutally I have no idea what I did, but adding a line to the `login` function of `downloader.py` fixed this problem for me.

```
## downloader.py

121     def login(self):
122         logging.info('Login...') 
123         driver = self.driver
124         driver.get(self.actions_class.login_url)
125         driver.delete_all_cookies()
126         add_cookies(driver, self.cookies)
 +          driver.get(self.actions_class.login_url)
128         logging.info('Login finished...')
```

**Comment by SnowySailor** [comment]
@chierinyan fwiw this didn't fix it for me so it may have been something else on your end
