### ISSUE TITLE
no module named 'PIL'

### ISSUE THREAD

**Issue by SergeyEjnpo** [xuzhengyi1995/Manga_downloader#15]
hi, could you please help me? What is it?

Traceback (most recent call last):
  File "C:/Users/Sergey/Downloads/Manga_downloader-master/Manga_downloader-master/main.py", line 5, in <module>
    from downloader import Downloader
  File "C:\Users\Sergey\Downloads\Manga_downloader-master\Manga_downloader-master\downloader.py", line 11, in <module>
    import PIL.Image as pil_image
ModuleNotFoundError: No module named 'PIL'

Process finished with exit code 1

**Comment by xuzhengyi1995** [comment]
This is because there is no pillow, Please run 
```shell
pip install Pillow
```
to install it.
Thank you.
