### ISSUE TITLE
I got something wrong when i downloaded page in BW！！ T_T

### ISSUE THREAD

**Issue by babyjin621** [xuzhengyi1995/Manga_downloader#156]
E:\**\Manga_downloader>python main.py
[INFO](undetected_chromedriver.patcher) 2023-12-20 12:29:56 : patching driver executable C:\Users\ASUS\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
[INFO](root) 2023-12-20 12:29:58 : Find action class, use BookwalkerTW class.
[INFO](root) 2023-12-20 12:29:58 : Login...
[INFO](root) 2023-12-20 12:30:04 : Login finished...
[INFO](root) 2023-12-20 12:30:04 : Starting download manga 1, imgdir: IMGDIR_FOR_URL_1
[INFO](root) 2023-12-20 12:30:04 : Loading Book page...
[INFO](root) 2023-12-20 12:30:05 : Book page Loaded...
[INFO](root) 2023-12-20 12:30:05 : Preparing for downloading...
[INFO](root) 2023-12-20 12:30:25 : Run before downloading...
[INFO](root) 2023-12-20 12:30:25 : Start download...
[ERROR](root) 2023-12-20 12:30:25 : Something wrong or download finished,Please check the error.png to see the web page.
Normally, you should logout and login, then renew the cookies to solve this problem.
[ERROR](root) 2023-12-20 12:30:25 : Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="pageSliderCounter"]"}
  (Session info: chrome=120.0.6099.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x012F6EE3+174339]
        (No symbol) [0x01220A51]
        (No symbol) [0x00F36FF6]
        (No symbol) [0x00F69876]
        (No symbol) [0x00F69C2C]
        (No symbol) [0x00F9BD42]
        (No symbol) [0x00F87054]
        (No symbol) [0x00F9A104]
        (No symbol) [0x00F86DA6]
        (No symbol) [0x00F61034]
        (No symbol) [0x00F61F8D]
        GetHandleVerifier [0x01394B1C+820540]
        sqlite3_dbdata_init [0x014553EE+653550]
        sqlite3_dbdata_init [0x01454E09+652041]
        sqlite3_dbdata_init [0x014497CC+605388]
        sqlite3_dbdata_init [0x01455D9B+656027]
        (No symbol) [0x0122FE6C]
        (No symbol) [0x012283B8]
        (No symbol) [0x012284DD]
        (No symbol) [0x01215818]
        BaseThreadInitThunk [0x77316359+25]
        RtlGetAppContainerNamedObjectPath [0x774B7B74+228]
        RtlGetAppContainerNamedObjectPath [0x774B7B44+180]

[INFO](root) 2023-12-20 12:30:25 : Finished download manga 1, imgdir: IMGDIR_FOR_URL_1
[ERROR](root) 2023-12-20 12:30:27 : This website has not been added...
Traceback (most recent call last):
  File "E:\**\Manga_downloader\main.py", line 43, in <module>
    downloader.download()
  File "E:\**\Manga_downloader\downloader.py", line 206, in download
    self.check_implementation(t_manga_url)
  File "E:\**\Manga_downloader\downloader.py", line 81, in check_implementation
    raise NotImplementedError
NotImplementedError

===============================
how can i do it？？ help me plz !!

**Comment by 7h3Cub3** [comment]
[ERROR](https://github.com/xuzhengyi1995/Manga_downloader/issues/root) 2023-12-20 12:30:25 : Something wrong or download finished,Please check the error.png to see the web page.
Normally, you should logout and login, then renew the cookies to solve this problem.

Did you do that ? it's usually a problem with login, you have to relog/regenerate your cookie auth.
