### ISSUE TITLE
bookwalker無法自動翻頁，收到error.png裏顯示第一頁

### ISSUE THREAD

**Issue by yatounoneko** [xuzhengyi1995/Manga_downloader#167]
我總共遇到了兩個問題，第一個問題如同#156，根據#149解決問題，然後遇到如下問題…

詳情：
```
D:\Manga_downloader-master>python .\main.py
[INFO](root) 2024-05-07 11:42:44 : Viewport dimensions [744, 1041]
[INFO](root) 2024-05-07 11:42:44 : Find action class, use BookwalkerTW class.
[INFO](root) 2024-05-07 11:42:44 : Login...
[INFO](root) 2024-05-07 11:42:50 : Login finished...
[INFO](root) 2024-05-07 11:42:50 : Starting download manga 1, imgdir: IMGDIR_FOR_URL_1
[INFO](root) 2024-05-07 11:42:50 : Loading Book page...
[INFO](root) 2024-05-07 11:42:52 : Book page Loaded...
[INFO](root) 2024-05-07 11:42:52 : Preparing for downloading...
[INFO](root) 2024-05-07 11:43:12 : Run before downloading...
[INFO](root) 2024-05-07 11:43:12 : Start download...
[ERROR](root) 2024-05-07 11:43:12 : Something wrong or download finished,Please check the error.png to see the web page.
Normally, you should logout and login, then renew the cookies to solve this problem.
[ERROR](root) 2024-05-07 11:43:12 : list index out of range
[INFO](root) 2024-05-07 11:43:12 : Finished download manga 1, imgdir: IMGDIR_FOR_URL_1
Exception ignored in: <function Chrome.__del__ at 0x000002C335137EC0>
Traceback (most recent call last):
  File "C:\Users\Nya\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\Nya\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] 句柄无效。
```

到了这一点,我注了掉下一个下载器.py裏的`option.add_argument('--headless')`,看到漫畫在首頁停了。 
不管是條漫還是單行本，都是停在首頁。 我透過#149的方法解決了登錄失敗的問題，但到這裏就無法繼續下去。

在解決#149遇到的問題時，我發現瀏覽器版本是我自己安裝的Chrome版本，而非zip内的版本。 我已經加入了path但似乎無效。  
![图片](https://github.com/xuzhengyi1995/Manga_downloader/assets/22129910/5eb431f3-1f77-42e0-a3c0-e050934ab995)  
不知道是否與chrome有關係... 
![image](https://github.com/xuzhengyi1995/Manga_downloader/assets/22129910/ddc5da13-3bb2-4037-88d5-2fdb84e1ce39)

**Comment by 995387611** [comment]
同问，我是按照说明一步步来的，以前都可以自动滚，现在只能手动下滚了

**Comment by yatounoneko** [comment]
意會錯了，新方法可用
函數改v9x
