### ISSUE TITLE
【已解决】批量下载时，第一本结束后无法开始下一本

### ISSUE THREAD

**Issue by persia7emily** [xuzhengyi1995/Manga_downloader#22]
[INFO](root) 2020-12-26 20:26:45 : Finished.
[INFO](root) 2020-12-26 20:26:45 : Finished download manga 1, imgdir: I:/Manga/1巻
[INFO](root) 2020-12-26 20:26:47 : Find action class, use CmoaJP class.
[INFO](root) 2020-12-26 20:26:47 : Starting download manga 2, imgdir: I:/Manga/2巻
[INFO](root) 2020-12-26 20:26:47 : Loading Book page...
[INFO](root) 2020-12-26 20:26:50 : Book page Loaded...
[INFO](root) 2020-12-26 20:26:50 : Preparing for downloading...
[INFO](root) 2020-12-26 20:26:55 : Run before downloading...

Traceback (most recent call last):
  File "D:/Program Files/Manga_downloader-master/main.py", line 47, in <module>
    downloader.download()
  File "D:\Program Files\Manga_downloader-master\downloader.py", line 178, in download
    self.download_book(t_img_dir)
  File "D:\Program Files\Manga_downloader-master\downloader.py", line 119, in download_book
    self.actions_class.before_download(driver)
  File "D:\Program Files\Manga_downloader-master\website_actions\cmoa_jp_actions.py", line 83, in before_download
    driver.execute_script('parent.closeTips()')
  File "C:\Users\Persia\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\Persia\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Persia\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: **Message: javascript error: Cannot read property 'style' of undefined**
  (Session info: headless chrome=87.0.4280.88)

总的来说一般有两种报错：
1.Cannot read property 'style' of undefined**
2.parent.closeTips is not a function

于是在cmoa_jp_actions.py里面把before_download()改成
    def before_download(self, driver):
        try:
            driver.execute_script('parent.closeTips()')
        except Exception as e:
            print(e)
就OK连续了。

**Comment by freezingyip** [comment]
可以問一下是如何開始的嗎?

**Comment by persia7emily** [comment]
> 可以問一下是如何開始的嗎?

不太清楚你在问什么，你是想问我遭遇的报错是怎么出现？还是说其他什么？
