### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by pilaco** [xuzhengyi1995/Manga_downloader#26]
I tried to use this script with firefox, but it didn't work well.

First thing I did was to download the webdriver for **firefox** which was **geckodriver**, then selenium and Pillow.

I downloaded repository and made some changes in **download.py** and **main.py**

`import PIL.Image as pil_image
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait`

`def get_driver(self):
        option = webdriver.FirefoxOptions()
        option.set_capability('unhandledPromptBehavior', 'accept')
        option.add_argument('high-dpi-support=1')
        option.add_argument('device-scale-factor=1')
        option.add_argument('force-device-scale-factor=1')
        option.add_argument(
            "user-agent=MMozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36")
        option.add_argument('window-size=%d,%d' % self.res)
        option.add_argument('headless')
        self.driver = webdriver.Firefox(firefox_options=option)`

I don't know anything about python, so I don't know if my changes are correct (I don't think they are).

so I ran main.py

````
python main.py 
[INFO](root) 2021-03-16 20:18:11 : Find action class, use BookwalkerJP class.
[INFO](root) 2021-03-16 20:18:11 : Login...
[INFO](root) 2021-03-16 20:18:21 : Login finished...
[INFO](root) 2021-03-16 20:18:21 : Starting download manga 1, imgdir: /home/****/raws/
[INFO](root) 2021-03-16 20:18:21 : Loading Book page...
[INFO](root) 2021-03-16 20:18:31 : Book page Loaded...
[INFO](root) 2021-03-16 20:18:31 : Preparing for downloading...
[INFO](root) 2021-03-16 20:18:51 : Run before downloading...
[INFO](root) 2021-03-16 20:18:51 : Start download...
[INFO](root) 2021-03-16 20:18:52 : Has 56 pages.
[ERROR](root) 2021-03-16 20:18:59 : Something wrong or download finished,Please check the error.png to see the web page.
Normally, you should logout and login, then renew the cookies to solve this problem.
[ERROR](root) 2021-03-16 20:18:59 : Message: SecurityError: The operation is insecure.

[INFO](root) 2021-03-16 20:18:59 : Finished download manga 1, imgdir: /home/****/raws/
[ERROR](root) 2021-03-16 20:19:01 : This website has not been added...
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    downloader.download()
  File "/home/****/Manga_downloader/downloader.py", line 172, in download
    self.check_implementation(t_manga_url)
  File "/home/****/Manga_downloader/downloader.py", line 77, in check_implementation
    raise NotImplementedError
NotImplementedError
````

the erro.png
![error](https://user-images.githubusercontent.com/22872431/111393340-5178ff80-8697-11eb-84d3-df97096ad38b.png)

What am I doing wrong? Any tips?

```
Arch Linux i686
Mozilla Firefox 79.0
```

**Comment by xuzhengyi1995** [comment]
I saw the `[ERROR](root) 2021-03-16 20:18:59 : Message: SecurityError: The operation is insecure.`, I think your modifications are right, but maybe the bookwalker changed the code of loading images to canvas.

I think the bookwalker has noticed this kind of downloading script, so they added some images not from the same source to the canvas so that we can not download the image by calling the `toDataURL` method.

If they are drawing some images to the canvas not from the orignal site, then we can not call the toDataURL method because of the security policy of the web browser.

Thank you to post the change of the website, I think we should think about another method to get the images, the worst situation is just make a screenshot of current webpage (I think this is not a bad idea and nobody can prevent us from doing this).

I will check the bookwalker and find out the reason, any future information will be post here.

Thank you again.

**Comment by pilaco** [comment]
There's something I didn't mention. I tested it on my other distro, because there is the version of chromium that supports 32bit chromedriver(in linux the 32bit chromedriver support goes up to version 62 of chromium/chrome) and is able to download the raws.

I think the problem is with firefox/geckodriver.

It would be nice if you tested with firefox too.

Thank you. What you are doing is helping a lot.
