### ISSUE TITLE
Unexpected keyword argument?

### ISSUE THREAD

**Issue by GNeric1** [xuzhengyi1995/Manga_downloader#31]
I'm probably an idiot, but every time I try to run, I get this issue

Traceback (most recent call last):
  File "C:\Users\User\Downloads\Manga_downloader-master\main.py", line 40, in <module>
    downloader = Downloader(**settings)
TypeError: __init__() got an unexpected keyword argument 'https://member.bookwalker.jp/app/03/webstore/cooperation?r=BROWSER_VIEWER/e8709557-64ab-4024-b1c4-d39d923534e8/https%3A%2F%2Fbookwalker.jp%2FholdBooks%2F'

**Comment by xuzhengyi1995** [comment]
Hello,

Could you post your `main.py`  here, thank you !

And I think it's time to change the configuration to a config file to make it easier to use (#10)

Thank you!

**Comment by crossface001** [comment]
hi, having the same error,

C:\Users\DELL>python D:\cmoa\Manga_downloader-master\main.py
Traceback (most recent call last):
  File "D:\cmoa\Manga_downloader-master\main.py", line 36, in <module>
    downloader = Downloader(**settings)
TypeError: __init__() got an unexpected keyword argument 'https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000071873_jp_0001&u0=0&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Ftitle%2F71873%2Fcookies'

**Comment by xuzhengyi1995** [comment]
> hi, having the same error,
> 
> C:\Users\DELL>python D:\cmoa\Manga_downloader-master\main.py
> Traceback (most recent call last):
> File "D:\cmoa\Manga_downloader-master\main.py", line 36, in
> downloader = Downloader(**settings)
> TypeError: **init**() got an unexpected keyword argument 'https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000071873_jp_0001&u0=0&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Ftitle%2F71873%2Fcookies'

I think you have some problem in `main.py`,

```python
settings = {
    # Manga urls, should be the same website
    'manga_url': [
        'https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000071873_jp_0001&u0=0&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Ftitle%2F71873%2F'
    ],
    # Your cookies
    'cookies': 'YOUR_COOKIES_HERE',
```

Please check if you have add the `'` after the URL, thank you!

**Comment by crossface001** [comment]
i had
  # Manga urls, should be the same website
    'https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000071873_jp_0001&u0=0&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Ftitle%2F71873%2F'

**Comment by xuzhengyi1995** [comment]
Hello,

Please notice the characters in the red circle.

![image](https://user-images.githubusercontent.com/29002064/114797060-e10fec00-9dc4-11eb-93db-656321097962.png)

The url should in the `'manga_url'` array, and the `'manga_url' : [ ],` should not be deleted.

Thank you!
