### ISSUE TITLE
Novels in coma.

### ISSUE THREAD

**Issue by Rouryi** [xuzhengyi1995/Manga_downloader#4]
For comics, it was successful, but for novels, an error occurred in coma.
The following is the error log.

Here's a [free novels](https://www.cmoa.jp/campaign/?type=list&genre=lightnovel&tag=free) for a sample.
[sample](https://www.cmoa.jp/bib/reader/main.html?cid=1101166036_jp_0001&u0=1&u1=0)

I would be grateful if you would fix it.
Thanks.

```[INFO](root)  : Login finished...
[INFO](root)  : Loading Book page...
[INFO:CONSOLE(1)] "The key "target-densitydpi" is not supported.", source: https://www.cmoa.jp/bib/reader/js/main.js?dmy=XXXXXXXX (1)
[INFO](root) : Book page Loaded...
[INFO](root) : Preparing for downloading...
[INFO:CONSOLE(1)] "The key "target-densitydpi" is not supported.", source: https://www.cmoa.jp/bib/reader/core/bib_script/scripts.js?dmy=XXXXXXXX (1)
[INFO:CONSOLE(1)] "Application Cache API use is deprecated and will be removed in M82, around May 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.", source: https://www.cmoa.jp/bib/reader/core/bib_script/scripts.js?dmy=XXXXXXXX (1)
[INFO](root) : Run before downloading...
Traceback (most recent call last):
  File ".\main.py", line 32, in <module>
    downloader.download()
  File "Manga_downloader-master\downloader.py", line 159, in download
    self.download_book()
  File "Manga_downloader-master\downloader.py", line 117, in download_book
    self.actions_class.before_download(driver)
  File "Manga_downloader-master\website_actions\cmoa_jp_actions.py", line 83, in before_download
    driver.execute_script('parent.closeTips()')
  File "Miniconda3\envs\scraping\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "Miniconda3\envs\scraping\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "Miniconda3\envs\scraping\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: parent.closeTips is not a function
  (Session info: headless chrome=83.0.4103.97)```

**Comment by xuzhengyi1995** [comment]
Thank you for your question.
I think maybe they are using different viewer for manga and novels.
I will check it during Sunday, 少々お待ちくださいね~
Thank you!

**Comment by xuzhengyi1995** [comment]
I'm sorry for the delay, but the novels use a very different viewer from the other website and the manga viewer, it will take more time to find a good way do download it, I'm very sorry but this should take some time, thank you!

**Comment by Rouryi** [comment]
I’m not in a hurry so no need to rush.
Thanks!

**Comment by xuzhengyi1995** [comment]
Hello,
Finally I have add this function, you can try it now~
The `manga_url` is the novel url: https://www.cmoa.jp/bib/reader/main.html?cid=1101166036_jp_0001&u0=1&u1=0
Thank you!

**Comment by Rouryi** [comment]
Thanks!
It worked fine!
