### ISSUE TITLE
關於擷取的圖片有白邊，及是否能增加批次提取的功能?

### ISSUE THREAD

**Issue by greenkero** [xuzhengyi1995/Manga_downloader#8]
您好：
首先感謝您開發這個工具，真的非常的好用與方便，且也省了不少時間～

有幾點請您參考參考：
1. BW的提取會有白邊的問題：使用PNG提取畫質非常的棒，但就是四周會有白邊的問題，不曉得能不能處理？
2. BW每次提取完，再次提取需要等候20分鐘，這是已經測試出來的數值，所以是否能新增個批次提取的功能？

以上建議僅供參考，在此表達萬分的感謝～
敬祝　順安

**Comment by xuzhengyi1995** [comment]
您好，感謝您對該工具的喜愛。
以下是對您問題的回答：
1.  對四周的白邊，本工具可以[在這裏](https://github.com/xuzhengyi1995/Manga_downloader/blob/fbee1f536f40fc7f7d9e316785cc28f3e2bc6153/main.py#L22)配置`'cut_image': (0,0,0,3),`（數據純屬示例），進行切邊操作，不過目前的程序切邊后會造成畫質損失，需要稍作修改輸出PNG即可，計劃在下一次提交時進行修改。
2.  BW對同一本漫畫會有限制，同一時間只能打開一本相同的漫畫；如果需要多次下載，可能需要首先關閉打開的網頁與工具，在網頁上登出后再登錄，並重新獲取Cooikes方可繼續下載。但是，非同一本漫畫應該不會出現該情況，如果有出現請告訴我，我將進行嘗試。關於批次提取，該功能的實現並不複雜且非常實用，是很好的提案，我將在之後的提交中加入。

由於目前工作較爲繁忙，工具的更新可能不及時，還請多多諒解，謝謝！

祝生活愉快！

**Comment by greenkero** [comment]
謝謝您的回覆：
經過測試，即使是不同一本書，提取間隔依然有20分鐘的限制。
提取完一本，再提取下一本時，如果少於20分鐘，就會顯示如下訊息：

[INFO](root) 2020-07-30 16:11:15 : Login finished...
[INFO](root) 2020-07-30 16:11:15 : Loading Book page...
[INFO](root) 2020-07-30 16:11:17 : Book page Loaded...
[INFO](root) 2020-07-30 16:11:17 : Preparing for downloading...
[INFO](root) 2020-07-30 16:11:37 : Run before downloading...
[INFO](root) 2020-07-30 16:11:37 : Start download...
[ERROR](root) 2020-07-30 16:11:38 : Something wrong or download finished,Please
check the error.png to see the web page.
Normally, you should logout and login, then renew the cookies to solve this prob
lem.
[ERROR](root) 2020-07-30 16:11:38 : list index out of range
[WARNING](urllib3.connectionpool) 2020-07-30 16:11:41 : Retrying (Retry(total=2,
 connect=None, read=None, redirect=None, status=None)) after connection broken b
y 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x027DA7F0>:
 Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒
絕連線。')': /session/8c61efddcd5fd2aa833d00a7417ffafd/window
[WARNING](urllib3.connectionpool) 2020-07-30 16:11:42 : Retrying (Retry(total=1,
 connect=None, read=None, redirect=None, status=None)) after connection broken b
y 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02818F40>:
 Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒
絕連線。')': /session/8c61efddcd5fd2aa833d00a7417ffafd/window
[WARNING](urllib3.connectionpool) 2020-07-30 16:11:43 : Retrying (Retry(total=0,
 connect=None, read=None, redirect=None, status=None)) after connection broken b
y 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02818F88>:
 Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒
絕連線。')': /session/8c61efddcd5fd2aa833d00a7417ffafd/window
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\http\client.
py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\http\client.
py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\http\client.
py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\http\client.
py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\http\client.
py", line 950, in send
    self.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object
 at 0x02818610>: Failed to establish a new connection: [WinError 10061] 無法連線
，因為目標電腦拒絕連線。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "11_main_手動.py", line 35, in <module>
    downloader.download()
  File "D:\Download\001\Manga_downloader\downloader.py", line 164, in download
    self.driver.close()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\selenium\webdriver\remote\webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\request.py", line 75, in request
    return self.request_encode_url(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5567
3): Max retries exceeded with url: /session/8c61efddcd5fd2aa833d00a7417ffafd/win
dow (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at
0x02818610>: Failed to establish a new connection: [WinError 10061] 無法連線，因
為目標電腦拒絕連線。'))

以上資訊提供給您參考
如果能處理白邊、及PNG再加上批次處理，這工具就太完美了…
感謝您的付出
敬祝 順安

**Comment by xuzhengyi1995** [comment]
您好，

根據之前的經驗，我還從未遇到20分鐘限制的問題，不知道是不是BW新的限制措施，我將于最近核實。
另外，如果方便，您可以查看或貼出檔案下的error.png文件以供參考。

白邊的處理目前可能仍然需要手動進行設置，無法自動進行，PNG在下一次的提交中一定會修改，批處理問題如果BW無新限制措施則也可以在下次提交中一并修改，如果有新的限制措施，可能不能及時修改。

謝謝！

**Comment by AlphaLiu** [comment]
Hi,

1. BW的時間限制是10分鐘。
2. 關於白邊，主要是BW的viewer給出來的值不一定不準確，主要是在width這裡會稍微寬幾個像素，手動把res的width減少幾個像素就好了，比如某社最新的(1128,1600)實際上是(1126,1600)。這要自己多嘗試了。

**Comment by xuzhengyi1995** [comment]
您好，

目前輸出圖片已經修正為png，並且可以一次下載多部漫畫，本人測試連續下載兩部漫畫成功，但是可能由於本地網絡狀況不佳/BW有限制，偶爾會出現加載圖片失敗的錯誤，還請您進行嘗試，謝謝！

關於白邊，非常感謝另一位使用者的提示，除了使用切邊以外，還可以手動將`res`的width減少幾個像素即可，目前該程序確實無法做到自動識別圖片分辨率，還請見諒。

目前批處理功能可以添加多個漫畫地址和存儲漫畫的文件夾，設置時還請一一對應，保證數量一致。

另外，目前批處理功能只能設置統一的分辨率，如果有分開設置的需求，還請提出，謝謝！

祝好！

**Comment by AlphaLiu** [comment]
Hi，

感谢添加批处理功能。我觉得分辨率还是要有分开设置才比较好，多谢！

**Comment by greenkero** [comment]
您好，是否願意願意私信我的信箱dyrlew@yahoo.com.tw
接下來的可能不適合公開討論
謝謝您

     在 2020年8月2日 星期日 下午04:33:15 [GMT+8]， XUZhengyi<notifications@github.com> 寫道：  
 
 


您好，

目前輸出圖片已經修正為png，並且可以一次下載多部漫畫，本人測試連續下載兩部漫畫成功，但是可能由於本地網絡狀況不佳/BW有限制，偶爾會出現加載圖片失敗的錯誤，還請您進行嘗試，謝謝！

關於白邊，非常感謝另一位使用者的提示，除了使用切邊以外，還可以手動將res的width減少幾個像素即可，目前該程序確實無法做到自動識別圖片分辨率，還請見諒。

目前批處理功能可以添加多個漫畫地址和存儲漫畫的文件夾，設置時還請一一對應，保證數量一致。

另外，目前批處理功能只能設置統一的分辨率，如果有分開設置的需求，還請提出，謝謝！

祝好！

**Comment by AlphaLiu** [comment]
> 您好，新版的啟動會有如下錯誤訊息 D:\Download\001\Manga_downloader-master_new>python main.py Traceback (most recent call last): File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package s\selenium\webdriver\common\service.py", line 72, in start self.process = subprocess.Popen (cmd, env=self.env, File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\subprocess.p y", line 854, in __init__ self._execute_child (args, executable, preexec_fn, close_fds, File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\subprocess.p y", line 1307, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess (executable, args, FileNotFoundError: [WinError 2] 系統找不到指定的檔案。 During handling of the above exception, another exception occurred: Traceback (most recent call last): File "main.py", line 40, in <module> downloader = Downloader (**settings) File "D:\Download\001\Manga_downloader-master_new\downloader.py", line 63, in __init__ self.init_function () File "D:\Download\001\Manga_downloader-master_new\downloader.py", line 94, in init_function self.get_driver () File "D:\Download\001\Manga_downloader-master_new\downloader.py", line 89, in get_driver self.driver = webdriver.Chrome (chrome_options=option) File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package s\selenium\webdriver\chrome\webdriver.py", line 73, in __init__ self.service.start () File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package s\selenium\webdriver\common\service.py", line 81, in start raise WebDriverException ( selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executabl e needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chrome driver/home 謝謝您

Hi ,
這個應該是你的chromedriver沒有找到。如果你之前可以使用的話，請檢查一下你的PATH是否改變了。如果不是請參照README文檔設置一下。

**Comment by greenkero** [comment]
啊！的確是忘了放進去，不好意思
現在可以正常運行了～
批次處理很方便，謝謝
至於固定的解析度，恩～

以下建議請參考看看

方法1：

看能不能類似像這樣
    # Resolution, (Width, Height), For coma this doesn't matter.
    'res_default': (1066, 1600),
    'res_1': (1066, 1600),
    'res_2': (1066, 1600),

_default是預設值，沒對應的自動抓取該數值

方法2：

    'manga_url': [

        'URL_1',

        'URL_2',
        'URL_3',
        'URL_4',
        'URL_5'

    # Resolution, (Width, Height), For coma this doesn't matter.
    'res_1': (1066, 1600),
    'res_2': (1066, 1600),
    'res_3': (1066, 1600)

當4、5沒有對應的數值時，通通去抓res_3也可以

另外有寫信給您，有點長，還請撥空閱讀，謝謝您～

**Comment by xuzhengyi1995** [comment]
大家好，
感謝大家的寶貴意見，如同在#10中的提議，可能更換爲配置文件后，並重新設計配置項會更加方便使用，我將會綜合考慮並進行修改，初步計劃使用toml格式的配置文件，如果大家有更好的建議還請提出，謝謝！
